import { describe, it, expect } from 'vitest'
import fc from 'fast-check'
import {
  resolveImportedProjectName,
  buildProjectUpdateOnDownloadComplete,
  buildImportPlaceholderName,
  isBlank,
  PROJECT_NAME_MAX_LENGTH,
} from '@/lib/video-import-service'

/**
 * Feature: link-import-project-name-fix
 *
 * 缺陷：链接导入视频未填写项目名称时，下载完成后未把 yt-dlp 真实标题
 * 回写到 project.name，名称恒为占位符 `导入视频 - {platform}`。
 *
 * 本文件用 fast-check 对修复后的两个纯函数（名称归一化 + 下载完成回写决策）
 * 做属性测试，直接导入生产代码以避免逻辑漂移。
 *
 * - Property 1: Bug Condition / Expected Behavior（未填写名称时回写真实标题，含空/超长边界）
 * - Property 2: Preservation（已填写名称时不被覆盖，且 videoUrl/status 恒被写入）
 */

// ========================
// 通用 Arbitraries
// ========================

/** 平台标识（与业务一致：抖音/快手/微信视频号等） */
const platformArb = fc.constantFrom('douyin', 'kuaishou', 'weixin', 'bilibili', 'unknown')

/** 仅含空白字符的标题（空串、空格、制表、换行等组合） */
const blankTitleArb = fc.string({
  unit: fc.constantFrom(' ', '\t', '\n', '\r', '\u3000'),
  minLength: 0,
  maxLength: 8,
})

/**
 * 任意标题（可能含首尾空白、超长、Unicode 宽字符）。
 * 组合 ASCII 串、grapheme 宽字符串，以及"前后包裹空白"的串以覆盖 trim 场景。
 */
const anyTitleArb = fc.oneof(
  fc.string({ minLength: 0, maxLength: 300 }),
  fc.string({ unit: 'grapheme', minLength: 0, maxLength: 200 }),
  fc
    .tuple(blankTitleArb, fc.string({ minLength: 0, maxLength: 50 }), blankTitleArb)
    .map(([head, body, tail]) => `${head}${body}${tail}`)
)

/** 非空白标题（trim 后非空），用于断言"等于归一化结果" */
const nonBlankTitleArb = anyTitleArb.filter((t) => t.trim().length > 0)

// ========================
// Property 1: Bug Condition / Expected Behavior
// 未填写名称时回写真实视频标题（trim → 截断到 100 → 空兜底）
// **Validates: Requirements 2.1, 2.2, 2.3**
// ========================

describe('Property 1: 未填写名称时回写真实视频标题（resolveImportedProjectName）', () => {
  it('非空白标题 → 等于 trim 后截断到 100 的结果，且长度 ≤ 100', () => {
    /**
     * **Validates: Requirements 2.1, 2.3**
     */
    fc.assert(
      fc.property(nonBlankTitleArb, platformArb, (title, platform) => {
        const result = resolveImportedProjectName(title, platform)
        const expected = title.trim().slice(0, PROJECT_NAME_MAX_LENGTH)

        expect(result).toBe(expected)
        expect(result.length).toBeLessThanOrEqual(PROJECT_NAME_MAX_LENGTH)
        // 非空白标题必产出非空名称
        expect(result.length).toBeGreaterThan(0)
      }),
      { numRuns: 300 }
    )
  })

  it('空 / 纯空白标题 → 非空兜底 `导入视频 - {platform}`', () => {
    /**
     * **Validates: Requirements 2.2**
     */
    fc.assert(
      fc.property(blankTitleArb, platformArb, (title, platform) => {
        const result = resolveImportedProjectName(title, platform)

        expect(result).toBe(buildImportPlaceholderName(platform))
        expect(isBlank(result)).toBe(false)
      }),
      { numRuns: 200 }
    )
  })

  it('null / undefined 标题 → 非空兜底', () => {
    /**
     * **Validates: Requirements 2.2**
     */
    fc.assert(
      fc.property(platformArb, (platform) => {
        expect(resolveImportedProjectName(null, platform)).toBe(buildImportPlaceholderName(platform))
        expect(resolveImportedProjectName(undefined, platform)).toBe(buildImportPlaceholderName(platform))
      }),
      { numRuns: 50 }
    )
  })

  it('任意输入产出的名称始终非空且 ≤ 100（全局不变量）', () => {
    /**
     * **Validates: Requirements 2.1, 2.2, 2.3**
     */
    fc.assert(
      fc.property(fc.option(anyTitleArb, { nil: undefined }), platformArb, (title, platform) => {
        const result = resolveImportedProjectName(title, platform)
        expect(result.length).toBeGreaterThan(0)
        expect(result.length).toBeLessThanOrEqual(PROJECT_NAME_MAX_LENGTH)
      }),
      { numRuns: 300 }
    )
  })

  it('纯函数：同一输入多次调用结果一致', () => {
    fc.assert(
      fc.property(fc.option(anyTitleArb, { nil: undefined }), platformArb, (title, platform) => {
        expect(resolveImportedProjectName(title, platform)).toBe(
          resolveImportedProjectName(title, platform)
        )
      }),
      { numRuns: 100 }
    )
  })
})

describe('Property 1: 下载完成回写决策在 nameAutoGenerated=true 时写入归一化名称', () => {
  it('nameAutoGenerated=true → update data 含 name = resolveImportedProjectName(title, platform)', () => {
    /**
     * **Validates: Requirements 2.1, 2.2, 2.3**
     */
    fc.assert(
      fc.property(
        fc.webUrl(),
        fc.option(anyTitleArb, { nil: undefined }),
        platformArb,
        (ossUrl, title, platform) => {
          const data = buildProjectUpdateOnDownloadComplete({
            ossUrl,
            nameAutoGenerated: true,
            title,
            platform,
          })

          expect(data.videoUrl).toBe(ossUrl)
          expect(data.status).toBe('PARSING')
          expect(data.name).toBe(resolveImportedProjectName(title, platform))
          expect(isBlank(data.name)).toBe(false)
        }
      ),
      { numRuns: 300 }
    )
  })
})

// ========================
// Property 2: Preservation
// 已填写名称时不被覆盖，且 videoUrl/status 恒被写入
// **Validates: Requirements 3.1, 3.2, 3.3**
// ========================

describe('Property 2: 已填写名称时下载完成不覆盖 name（buildProjectUpdateOnDownloadComplete）', () => {
  it('nameAutoGenerated=false → update data 不含 name（保持用户输入）', () => {
    /**
     * **Validates: Requirements 3.1**
     */
    fc.assert(
      fc.property(
        fc.webUrl(),
        fc.option(anyTitleArb, { nil: undefined }),
        platformArb,
        (ossUrl, title, platform) => {
          const data = buildProjectUpdateOnDownloadComplete({
            ossUrl,
            nameAutoGenerated: false,
            title,
            platform,
          })

          // 名称不被改动：update data 不包含 name 键
          expect('name' in data).toBe(false)
        }
      ),
      { numRuns: 300 }
    )
  })

  it('无论是否回写名称，videoUrl + status=PARSING 恒被写入（既有字段不被挤掉）', () => {
    /**
     * **Validates: Requirements 3.2**
     */
    fc.assert(
      fc.property(
        fc.webUrl(),
        fc.boolean(),
        fc.option(anyTitleArb, { nil: undefined }),
        platformArb,
        (ossUrl, nameAutoGenerated, title, platform) => {
          const data = buildProjectUpdateOnDownloadComplete({
            ossUrl,
            nameAutoGenerated,
            title,
            platform,
          })

          expect(data.videoUrl).toBe(ossUrl)
          expect(data.status).toBe('PARSING')
        }
      ),
      { numRuns: 300 }
    )
  })
})

// ========================
// 意图判定：isBlank 与 nameAutoGenerated 语义
// **Validates: Requirements 1.1, 3.1**
// ========================

describe('isBlank：未填写名称（undefined/空/纯空白）判定', () => {
  it('undefined / 空串 / 纯空白 → true；含非空白字符 → false', () => {
    /**
     * **Validates: Requirements 1.1**
     */
    expect(isBlank(undefined)).toBe(true)
    expect(isBlank('')).toBe(true)
    expect(isBlank('   ')).toBe(true)
    expect(isBlank('\t\n')).toBe(true)

    fc.assert(
      fc.property(nonBlankTitleArb, (s) => {
        expect(isBlank(s)).toBe(false)
      }),
      { numRuns: 200 }
    )
  })
})
