import { prisma } from '@/lib/shared/db'
import { videoDownloadQueue } from '@/lib/shared/queue'
import { validateShareLink, type ExtendedPlatform } from '@/lib/shared/validate-share-link'
export type { ValidateResult, ExtendedPlatform } from '@/lib/shared/validate-share-link'

// 重新导出 validateShareLink，确保已有导入路径不破坏
export { validateShareLink }

// ========================
// 项目名称归一化（链接导入）
// ========================

/** 项目名称长度上限（字符），超出部分截断 */
export const PROJECT_NAME_MAX_LENGTH = 100

/**
 * 判断字符串是否"空白"：undefined/null、空串或仅含空白字符时返回 true。
 * 用于判定用户是否填写了项目名称（即是否触发 bug 条件 / 名称是否需自动生成）。
 */
export function isBlank(s: string | null | undefined): boolean {
  return s == null || s.trim() === ''
}

/**
 * 构造链接导入项目的占位符名称（用户未填写名称时使用）。
 * 建项目时的占位符与下载完成空标题兜底复用同一构造方式，避免文案漂移。
 */
export function buildImportPlaceholderName(platform: string): string {
  return `导入视频 - ${platform}`
}

/**
 * 将 yt-dlp 原始视频标题归一化为最终项目名称：
 * 先 trim，空（含纯空白/缺失）则兜底为占位符，否则截断到长度上限。
 * 纯函数、无副作用，便于属性测试。
 * @param rawTitle yt-dlp 返回的原始标题（可能为 null/undefined/含首尾空白/超长）
 * @param platform 平台标识，用于空标题兜底
 * @returns 非空、长度 ≤ PROJECT_NAME_MAX_LENGTH 的项目名称
 */
export function resolveImportedProjectName(
  rawTitle: string | null | undefined,
  platform: string
): string {
  const trimmed = (rawTitle ?? '').trim()
  if (trimmed === '') {
    // 兜底：与建项目占位符一致，保证名称非空
    return buildImportPlaceholderName(platform)
  }
  // 先 trim 再截断到上限（与 truncate(trim(title), 100) 定义一致）
  return trimmed.slice(0, PROJECT_NAME_MAX_LENGTH)
}

/** 下载完成回写 Project 时的输入意图 */
interface DownloadCompleteUpdateInput {
  /** 上传 OSS 后的视频访问 URL */
  ossUrl: string
  /** 名称是否为系统自动生成（用户未填写）：true 时才允许用真实标题回写 name */
  nameAutoGenerated: boolean
  /** yt-dlp 返回的视频标题 */
  title: string | null | undefined
  /** 平台标识 */
  platform: string
}

/** 下载完成回写 Project 的字段（name 为可选，仅自动生成时出现） */
interface DownloadCompleteUpdateData {
  videoUrl: string
  status: 'PARSING'
  name?: string
}

/**
 * 计算"下载完成"时对 Project 的回写字段（纯函数，无副作用，便于属性测试）。
 * - 恒写入 videoUrl 与 status=PARSING（既有行为不变）。
 * - 仅当 nameAutoGenerated 为 true 时追加归一化后的 name；否则完全不触碰 name，
 *   保证用户已填写的名称不被真实标题覆盖。
 */
export function buildProjectUpdateOnDownloadComplete(
  input: DownloadCompleteUpdateInput
): DownloadCompleteUpdateData {
  const data: DownloadCompleteUpdateData = {
    videoUrl: input.ossUrl,
    status: 'PARSING',
  }
  if (input.nameAutoGenerated) {
    data.name = resolveImportedProjectName(input.title, input.platform)
  }
  return data
}

// ========================
// 视频导入服务核心逻辑
// ========================

interface ImportResult {
  projectId: string
  taskId: string
  platform: ExtendedPlatform
}

/**
 * 验证链接并创建导入任务
 * 流程：验证链接 → 创建 Project（status=DOWNLOADING）→ 创建 VideoDownloadTask → 入队
 */
export async function validateAndImport(
  userId: string,
  url: string,
  projectName?: string
): Promise<ImportResult> {
  // 1. 验证链接格式（支持从分享文案中自动提取 URL）
  const validation = validateShareLink(url)
  if (!validation.valid || !validation.platform) {
    throw new Error(validation.error || '链接验证失败')
  }

  // 使用提取后的纯净 URL（而非用户原始输入的分享文案）
  const actualUrl = validation.extractedUrl || url.trim()

  // 判定用户是否填写了项目名称：未填写（空/纯空白）则名称为系统自动生成，
  // 下载完成后允许用 yt-dlp 真实标题回写覆盖
  const nameAutoGenerated = isBlank(projectName)

  // 2. 创建 Project，状态设为 DOWNLOADING
  //    未填写名称时落占位符（保持 name 非空约束），下载完成后再回写真实标题
  const project = await prisma.project.create({
    data: {
      userId,
      name: nameAutoGenerated
        ? buildImportPlaceholderName(validation.platform)
        : projectName!.trim(),
      status: 'DOWNLOADING',
    },
  })

  // 3. 创建 VideoDownloadTask
  const task = await prisma.videoDownloadTask.create({
    data: {
      projectId: project.id,
      userId,
      sourceUrl: actualUrl,
      platform: validation.platform,
      status: 'PENDING',
      progress: 0,
    },
  })

  // 4. 添加到下载队列（携带 nameAutoGenerated 意图，供下载完成时决定是否回写名称）
  await videoDownloadQueue.add('download-video', {
    taskId: task.id,
    projectId: project.id,
    sourceUrl: actualUrl,
    platform: validation.platform,
    nameAutoGenerated,
  })

  return {
    projectId: project.id,
    taskId: task.id,
    platform: validation.platform,
  }
}

/**
 * 查询导入（下载）进度
 * @param projectId - 项目 ID
 * @param userId - 用户 ID（确保只能查询自己的任务）
 */
export async function getImportStatus(projectId: string, userId: string) {
  const task = await prisma.videoDownloadTask.findFirst({
    where: { projectId, userId },
    orderBy: { createdAt: 'desc' },
  })

  if (!task) return null

  return {
    taskId: task.id,
    status: task.status,
    progress: task.progress,
    errorMsg: task.errorMsg,
    platform: task.platform,
  }
}
